<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net6.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <UseWPF>true</UseWPF>
	<UseWindowsForms>true</UseWindowsForms>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="Themes\Assets\Add.png" />
    <None Remove="Themes\Assets\AddTab.png" />
    <None Remove="Themes\Assets\Arrow_Down.png" />
    <None Remove="Themes\Assets\Arrow_Left.png" />
    <None Remove="Themes\Assets\Arrow_Right.png" />
    <None Remove="Themes\Assets\Arrow_Up.png" />
    <None Remove="Themes\Assets\BC.png" />
    <None Remove="Themes\Assets\Beat.png" />
    <None Remove="Themes\Assets\Camera.png" />
    <None Remove="Themes\Assets\Close.png" />
    <None Remove="Themes\Assets\CloseTab.png" />
    <None Remove="Themes\Assets\Coloration.png" />
    <None Remove="Themes\Assets\colorChart.PNG" />
    <None Remove="Themes\Assets\ColorWheel.png" />
    <None Remove="Themes\Assets\Composition.png" />
    <None Remove="Themes\Assets\Copy.png" />
    <None Remove="Themes\Assets\Cube.png" />
    <None Remove="Themes\Assets\Cube_Col.png" />
    <None Remove="Themes\Assets\DeleteLayer.png" />
    <None Remove="Themes\Assets\DragHandler.png" />
    <None Remove="Themes\Assets\Edit.png" />
    <None Remove="Themes\Assets\Effect.png" />
    <None Remove="Themes\Assets\Entity.png" />
    <None Remove="Themes\Assets\Folder.png" />
    <None Remove="Themes\Assets\Folder_Opened.png" />
    <None Remove="Themes\Assets\HSL.png" />
    <None Remove="Themes\Assets\HueCircle.png" />
    <None Remove="Themes\Assets\IsChecked.png" />
    <None Remove="Themes\Assets\LayerScene.png" />
    <None Remove="Themes\Assets\Mask.png" />
    <None Remove="Themes\Assets\Maximize.png" />
    <None Remove="Themes\Assets\Menu.png" />
    <None Remove="Themes\Assets\MeshLight.png" />
    <None Remove="Themes\Assets\Minimize.png" />
    <None Remove="Themes\Assets\Network.png" />
    <None Remove="Themes\Assets\NewLayer.png" />
    <None Remove="Themes\Assets\NotVisible.png" />
    <None Remove="Themes\Assets\Paste.png" />
    <None Remove="Themes\Assets\Play.png" />
    <None Remove="Themes\Assets\Playlist.png" />
    <None Remove="Themes\Assets\Rename.png" />
    <None Remove="Themes\Assets\Reset.png" />
    <None Remove="Themes\Assets\Resource.png" />
    <None Remove="Themes\Assets\Scene.png" />
    <None Remove="Themes\Assets\Scheduler.png" />
    <None Remove="Themes\Assets\Settings.png" />
    <None Remove="Themes\Assets\Size.png" />
    <None Remove="Themes\Assets\Stop.png" />
    <None Remove="Themes\Assets\Sub.png" />
    <None Remove="Themes\Assets\Texture.png" />
    <None Remove="Themes\Assets\Transform3D.png" />
    <None Remove="Themes\Assets\Transparent_Bg.png" />
    <None Remove="Themes\Assets\Visible.png" />
    <None Remove="Themes\Assets\Warning.png" />
    <None Remove="Themes\Assets\World.png" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="ColorMine" Version="1.1.3" />
    <PackageReference Include="CommunityToolkit.Mvvm" Version="8.2.2" />
    <PackageReference Include="Expression.Interaction" Version="3.0.40218" />
    <PackageReference Include="gong-wpf-dragdrop" Version="3.2.1" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="8.0.0" />
    <PackageReference Include="MvvmDialogs" Version="9.1.2" />
    <PackageReference Include="WatsonTcp" Version="6.0.6" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\CMiX.Core\CMiX.Core.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Resource Include="Themes\Assets\Add.png" />
    <Resource Include="Themes\Assets\AddTab.png" />
    <Resource Include="Themes\Assets\Arrow_Down.png" />
    <Resource Include="Themes\Assets\Arrow_Left.png" />
    <Resource Include="Themes\Assets\Arrow_Right.png" />
    <Resource Include="Themes\Assets\Arrow_Up.png" />
    <Resource Include="Themes\Assets\BC.png" />
    <Resource Include="Themes\Assets\Beat.png" />
    <Resource Include="Themes\Assets\Camera.png" />
    <Resource Include="Themes\Assets\Close.png" />
    <Resource Include="Themes\Assets\CloseTab.png" />
    <Resource Include="Themes\Assets\Coloration.png" />
    <Resource Include="Themes\Assets\colorChart.PNG" />
    <Resource Include="Themes\Assets\ColorWheel.png" />
    <Resource Include="Themes\Assets\Composition.png" />
    <Resource Include="Themes\Assets\Copy.png" />
    <Resource Include="Themes\Assets\Cube.png" />
    <Resource Include="Themes\Assets\Cube_Col.png" />
    <Resource Include="Themes\Assets\DeleteLayer.png" />
    <Resource Include="Themes\Assets\DragHandler.png" />
    <Resource Include="Themes\Assets\Edit.png" />
    <Resource Include="Themes\Assets\Effect.png" />
    <Resource Include="Themes\Assets\Entity.png" />
    <Resource Include="Themes\Assets\Folder.png" />
    <Resource Include="Themes\Assets\Folder_Opened.png" />
    <Resource Include="Themes\Assets\HSL.png" />
    <Resource Include="Themes\Assets\HueCircle.png" />
    <Resource Include="Themes\Assets\IsChecked.png" />
    <Resource Include="Themes\Assets\LayerScene.png" />
    <Resource Include="Themes\Assets\Mask.png" />
    <Resource Include="Themes\Assets\Maximize.png" />
    <Resource Include="Themes\Assets\Menu.png" />
    <Resource Include="Themes\Assets\MeshLight.png" />
    <Resource Include="Themes\Assets\Minimize.png" />
    <Resource Include="Themes\Assets\Network.png" />
    <Resource Include="Themes\Assets\NewLayer.png" />
    <Resource Include="Themes\Assets\NotVisible.png" />
    <Resource Include="Themes\Assets\Paste.png" />
    <Resource Include="Themes\Assets\Play.png" />
    <Resource Include="Themes\Assets\Playlist.png" />
    <Resource Include="Themes\Assets\Rename.png" />
    <Resource Include="Themes\Assets\Reset.png" />
    <Resource Include="Themes\Assets\Resource.png" />
    <Resource Include="Themes\Assets\Scene.png" />
    <Resource Include="Themes\Assets\Scheduler.png" />
    <Resource Include="Themes\Assets\Settings.png" />
    <Resource Include="Themes\Assets\Size.png" />
    <Resource Include="Themes\Assets\Stop.png" />
    <Resource Include="Themes\Assets\Sub.png" />
    <Resource Include="Themes\Assets\Texture.png" />
    <Resource Include="Themes\Assets\Transform3D.png" />
    <Resource Include="Themes\Assets\Transparent_Bg.png" />
    <Resource Include="Themes\Assets\Visible.png" />
    <Resource Include="Themes\Assets\Warning.png" />
    <Resource Include="Themes\Assets\World.png" />
  </ItemGroup>

  <ItemGroup>
    <Compile Update="Views\Managers\LightSelectionPanel.xaml.cs">
      <SubType>Code</SubType>
    </Compile>
    <Compile Update="Views\Managers\CameraSelectionPanel.xaml.cs">
      <SubType>Code</SubType>
    </Compile>
    <Compile Update="Views\Managers\MaterialSelectionPanel.xaml.cs">
      <SubType>Code</SubType>
    </Compile>
    <Compile Update="Views\Messenger\ServerSelectionPanel.xaml.cs">
      <SubType>Code</SubType>
    </Compile>
    <Compile Update="Views\Modifiers\Light\RandomRotation.xaml.cs">
      <SubType>Code</SubType>
    </Compile>
  </ItemGroup>

</Project>
