<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0-windows</TargetFramework>
      <CopyLocalLockFileAssemblies>true</CopyLocalLockFileAssemblies>
      <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>disable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="CommunityToolkit.Mvvm" Version="8.4.0" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="8.0.1" />
    <PackageReference Include="Scrutor" Version="6.1.0" />
    <PackageReference Include="StackExchange.Redis" Version="2.8.31" />
    <PackageReference Include="VL.CoreLib" Version="2025.7.0" />
    <PackageReference Include="VL.Serialization.MessagePack" Version="2025.7.0" />
  </ItemGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="CMiX.Core.Tests" />
  </ItemGroup>

  <ItemGroup>
    <None Update="appsettings.json">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
  </ItemGroup>

</Project>
