<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net6.0-windows</TargetFramework>
      <CopyLocalLockFileAssemblies>true</CopyLocalLockFileAssemblies>
      <ImplicitUsings>enable</ImplicitUsings>
     <OutputPath>..\lib</OutputPath>
    <Nullable>disable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="AutoMapper" Version="13.0.1" />
    <PackageReference Include="AutoMapper.Collection" Version="10.0.0" />
    <PackageReference Include="Ceras" Version="4.1.7" />
    <PackageReference Include="CommunityToolkit.Mvvm" Version="8.2.2" />
    <PackageReference Include="FluentScheduler" Version="5.5.1" />
    <PackageReference Include="gong-wpf-dragdrop" Version="3.2.1" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="8.0.0" />
    <PackageReference Include="MvvmDialogs" Version="9.1.2" />
    <PackageReference Include="Scrutor" Version="4.2.2" />
    <PackageReference Include="WatsonTcp" Version="6.0.5" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Rendering\Lights\Modifiers\" />
    <Folder Include="Services\" />
  </ItemGroup>

</Project>
